---
title: "Computing troubleshooting"
---

Se tes dificultades para lanzar unha sesión de **Python** desde o teu usuario reservado, diríxete a [a este email](mailto://asanchez@uvigo.gal).

- Se o estado mostra algo que non sexa "operativo", isto significa que hai un incidente coñecido cos contedores.
    Volve máis tarde para ver se se resolveu.
    Se pronto hai un prazo, publique no foro do curso para facernos saber que hai un problema.
    Podemos examinar a rapidez que se pode resolver e decidir que facer sobre o prazo en consecuencia.
    Nota: non prevemos que isto suceda regularmente, os sistemas están a operar unha gran maioría do tempo.

- Se o estado mostra "operativo", isto significa que o sistema está previsto que funcione.
    Comprobe a súa conexión a Internet, se é necesario, reinicie o ordenador para garantir unha nova conexión nova.
    Se o teu problema persiste, publique no foro do curso con detalles sobre o que probaches e os erros que ves (incluíndo erros e/ou capturas de pantalla verbatim).

- De calquera xeito tamén podes cubrir o formulario seguinte:


<iframe width="640px" height="480px" src="https://forms.office.com/e/KYC2MmuvRZ?origin=lprLink" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen 
msallowfullscreen> </iframe>

Intentaremos, na medida da nosas posibilidades solucionar o problema.
